"use strict"
!function(t){function i(t,i){for(var s=0;s<t.length;s++)t[s].call(void 0,i)}function s(t,i,s,r){this.reset(t,i,s,r)}function r(t,i){for(var s=0,r=0;r<t.length;r++)s=s*i+t[r]
return s}var n=25,e=.001
s.cubicBezier=function(t,i,s,n){return function(o){for(var h=[3*t-3*s+1,-6*t+3*s,3*t,-o],u=[9*t-9*t+3,-12*t+6*s,3*t],c=[3*i-3*n+1,-6*i+3*n,3*i,0],a=r(h,o),p=-r(h,a);Math.abs(p)>e;)a+=p/Math.max(r(u,a),1),p=-r(h,a)
return r(c,a)}},s.linear=function(t){return t},s.easeIn=s.cubicBezier(.42,0,1,1),s.easeOut=s.cubicBezier(0,0,.58,1),s.ease=s.cubicBezier(.25,.1,.25,1),s.easeInOut=s.cubicBezier(.42,0,.58,1),s.prototype.start=function(){return this._counter||(this._counter=setInterval(function(t){t.progress(t._progress+t._step)},this._interval,this)),this._started=!0,this},s.prototype.stop=function(){return this._counter&&(clearInterval(this._counter),this._counter=null),this},s.prototype.progress=function(t){if(0>t&&(t=0),t>1&&(t=1),this._progress!==t){this._progress=t
for(var s in this._first)this.target[s]=this._first[s]+this._delta[s]*this._func(t)
i(this._callback,this),this._loop?(1==t&&this._step>0||0==t&&this._step<0)&&(this._step=-this._step):1==t&&i(this.stop()._onfinish,this)}return this},s.prototype.restart=function(){return this.stop().start()},s.prototype.cancel=function(){return this.stop().progress(0)},s.prototype.finish=function(){return this.stop().progress(1)},s.prototype.running=function(){return!!this._counter},s.prototype.reset=function(t,i,r,e){if(this.stop(),this.target=t,this.data=null,this._ms=r,this._step=1e3/(r*n),this._callback=[],this._interval=1e3/n,this._counter=null,this._first={},this._delta={},this._progress=0,this._onfinish=[],this._started=!1,this._func=s.linear,this._loop=!1,e)for(var o in e){var h=e[o]
this._first[h]=+t[h],this._delta[h]=i[h]-this._first[h]}else for(var h in i)this._first[h]=+t[h],this._delta[h]=i[h]-this._first[h]
return this},s.prototype.animate=function(t){return this._callback.push(t),this},s.prototype.then=function(t){return this._onfinish.push(t),this._started&&!this._counter&&t.call(void 0,this),this},s.prototype.setData=function(t){return this.data=t,this},s.prototype.setFunc=function(t){return this._func=t,this},s.prototype.fps=function(t){return this._interval=1e3/t,this._step=1e3/(this._ms*t),this._counter&&this.restart(),this},s.prototype.loop=function(t){this._loop=!!t},s.nullAnimation=function(){var t=new s([],[],1)
return t.start=function(){return this._started=!0,this.finish(),this},t.progress=function(){return this.stop(),i(this._callback,this),i(this._onfinish,this),this},t},t.Animate=s}(window)
